name = "LibFTD2XX"
uuid = "85e77ee8-8498-5435-b1ed-98efe5aa7d59"
version = "0.3.0"

[deps]
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
libftd2xx_jll = "66e46913-a265-5186-af4c-28555ad2a364"

[compat]
julia = "^1.3"
libftd2xx_jll = "^1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
